### ISSUE TITLE
tried to register new user, get "pass is undefined"

### ISSUE THREAD

**Issue by nicholascloud** [adamlucz90/RecordmateAngular#11]
I tried to register myself as a new user, and in the console I see the following error:

```
GET /templates/register-index.html 200 0.676 ms - 2077
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: pass is not defined
    at /home/nicholascloud/projects/launchcode/lucz-recordmate/api/controllers/authenticate.js:34:23
    at Query.<anonymous> (/home/nicholascloud/projects/launchcode/lucz-recordmate/node_modules/mongoose/lib/model.js:3327:16)
    at /home/nicholascloud/projects/launchcode/lucz-recordmate/node_modules/mongoose/node_modules/kareem/index.js:259:21
    at /home/nicholascloud/projects/launchcode/lucz-recordmate/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

I'm guessing this has to do with the change you made to prevent the password from being forced to be all lowercase: https://github.com/adamlucz90/RecordmateAngular/commit/aa13b964bc3cc7e742a5179ca1909c80231ce219#diff-9368274a153e82fe352095274a555335L14

**Comment by adamlucz90** [comment]
This is fixed.  Just needed to replace a variable I was using when I was setting the password to lowercase.  Great catch though!
