### ISSUE TITLE
unable to run project due to syntax error

### ISSUE THREAD

**Issue by nicholascloud** [adamlucz90/RecordmateAngular#14]
When I tried to run the project, I received this error:

```
/Users/nicholascloud/projects/launchcode/lucz-recordmate/api/routes/router.js:17
router.post('/friendlistRender', ctrl.Friend.friendlistRender);
                                 ^

ReferenceError: ctrl is not defined
    at Object.<anonymous> (/Users/nicholascloud/projects/launchcode/lucz-recordmate/api/routes/router.js:17:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nicholascloud/projects/launchcode/lucz-recordmate/api_app.js:15:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nicholascloud/projects/launchcode/lucz-recordmate/bin/server.js:7:11)
    at Module._compile (module.js:409:26)
```

Turns out to be a simple syntax issue. On [this line](https://github.com/adamlucz90/RecordmateAngular/blob/master/api/routes/router.js#L17) `ctrl.Friend` should be `ctrlFriend`.

**Comment by adamlucz90** [comment]
I noticed that earlier and fixed it.  Just forgot to add a new commit.  Whoops!
